### ISSUE TITLE
Use expressions instead of strings?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaFEM/FEMBasis.jl#16]
Passing Julia expressions as strings into `create_basis` seems really odd. Is there a reason it's not just an expression?

**Comment by ahojukka5** [comment]
Hmm. [looks](https://github.com/JuliaFEM/FEMBasis.jl/blob/master/src/create_basis.jl#L164) that strings is immediately parsed to expression. Does the string approach look odd in a sense that it's causing some particular problem and only expression as input argument should be used?

**Comment by ChrisRackauckas** [comment]
Well, strings have to be stack-allocated while symbols are immutable, so while the performance hit wouldn't be big it would create a lot of unnecessary small allocation which could in theory build up. And most APIs use symbols anyways. Also, symbols are immutable so they are pure so literals and constants which are symbols can propagate further in compiler optimizations which are happening down the line.
