### ISSUE TITLE
Number of Warning messages in FEMBasis

### ISSUE THREAD

**Issue by ovainola** [JuliaFEM/FEMBasis.jl#28]
FEMBasis seems to fill stdout log with warnings, f.ex.:
https://travis-ci.org/JuliaFEM/JuliaFEM.jl/jobs/428170944

Any idea where this roots from?

**Comment by ahojukka5** [comment]
See issue #9. Also https://github.com/JuliaMath/Calculus.jl/issues/128.

**Comment by ovainola** [comment]
I guess this can be closed due to being dublicate
