### ISSUE TITLE
Register v0.3.1

### ISSUE THREAD

**Issue by ahojukka5** [JuliaFEM/FEMBasis.jl#36]
@JuliaRegistrator register()

**Comment by ahojukka5** [comment]
@JuliaRegistrator register()

**Comment by mauro3** [comment]
You have to add version bounds into your Project.toml to make the automerge work:
```
[compat]
julia = "≥ 1.0"
Calculus = "0.5"
Tensors = "1"
```
should do the trick.  (Note std-libs don't need bounds)

**Comment by ahojukka5** [comment]
Added. Thanks.

@JuliaRegistrator register()

**Comment by ahojukka5** [comment]
@JuliaRegistrator register()

**Comment by ahojukka5** [comment]
No ei tule mitään...
@JuliaRegistrator register()
